# Generated by Django 3.1.4 on 2021-01-07 20:57

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20210105_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Test'),
            preserve_default=False,
        ),
    ]
